### ISSUE TITLE
Create "Increment a decimal-coded number" problem

### ISSUE THREAD

**Issue by lumig242** [google/tie#127]

**Comment by arbiter527** [comment]
Cooperate with Shenggu to create this problem

**Comment by lumig242** [comment]
PR: #133

**Comment by arbiter527** [comment]
Should we add some follow ups like:
1. The input is a negative number.
2. The input adds two digits number, like 11 or 15, rather than just 1.
3. The input number is not decimal-coded, but binary coded or hexadecimal.

**Comment by seanlip** [comment]
Those are interesting follow-ups, thanks for suggesting them!

I think that that would be nice, actually -- it gives the student some additional practice with the concept so that they can build mastery. It's fine to do those in a separate PR if you like, but let's make sure an issue is filed for that.

**Comment by seanlip** [comment]
Completed in #175.
