### ISSUE TITLE
Add tests in clients/domain

### ISSUE THREAD

**Issue by lumig242** [google/tie#222]
- [x] CodeEvalResultObjectFactory.js

- [x] CorrectnessTestObjectFactory.js

- [x] FeedbackObjectFactory.js

- [x] FeedbackParagraphObjectFactory.js

- [x] QuestionObjectFactory.js

- [x] SnapshotObjectFactory.js

**Comment by alblin** [comment]
note - the one uncovered line in  FeedbackParagraphObjectFactory.js I think is unreachable by design because of the static methods to create paragraphs enforce that they are always type code or text. Thus, it should never be any other type, which is what the uncovered line requires to throw an error.

**Comment by lumig242** [comment]
[Code](https://github.com/google/tie/blob/master/client/domain/FeedbackParagraphObjectFactory.js#L26) here for reference. I think this is true and it is safe to delete the check.

**Comment by alblin** [comment]
^above code deleted in most recent PR #229 . achieved 100% karma coverage for domain/
