### ISSUE TITLE
Wrap student code more carefully.

### ISSUE THREAD

**Issue by seanlip** [google/tie#257]
To reproduce:

1. Open the TIE app and navigate to the RLE problem.
2. Type the following code:
```
def encoded(a):
    return ""

def encode(word):
    return ""
```
3. Run the code. A syntax error will be displayed.

(Note that, if "encoded" in the sample code is replaced by "encoxded", this issue no longer arises.)

The issue occurs because the code preprocessing process replaces the first line of code with `StudentCode(self, ).encoded(a)`, since it sees a function starting with the string "encode" and naively assumes that this needs to be wrapped. Instead, however, it should note that the string doesn't terminate after "encode" -- and, based on that check, it should not do the replacement.

(Thanks @BenjaminHolland for noting this.)

**Comment by BenjaminHolland** [comment]
Specific Location:
/client/services/code_preprocessors/PythonCodePreprocessorService.js::_transformCodeToInstanceMethods() line 71

**Comment by BenjaminHolland** [comment]
Uploading instrumented run to illustrate issue more clearly.
[Issue257 Error Illustration.txt](https://github.com/google/tie/files/957219/Issue257.Error.Illustration.txt)

**Comment by BenjaminHolland** [comment]
Since python treats methods and functions as first-class objects, we should note that the check should be something along the lines of the following:

trim all spaces immediately following the found name.
Check the next character for a valid variable name character. If there is one, do not wrap the function. 
if the next non-whitespace character is ( ) ] or , wrap the function as normal.
if the next non-whitespace character is not in the previous groups, this is a python syntax error
if the statement is an assignment and the next whitespace character is a \n, wrap the function as normal.
otherwise, there's a python syntax error.
