### ISSUE TITLE
Architecture Request: UI Modification Callback for Buggy Functions

### ISSUE THREAD

**Issue by BenjaminHolland** [google/tie#285]
It would be useful for people creating questions to be able to cause UI changes in response to buggy functions. Minimum, we should be able to "call out" the different sections, like the instruction box. 

I suggest creating a new service that can be passed into a callback defined in a question that allows users to start and stop callout animations and do other things, like spawn popups.

**Comment by seanlip** [comment]
Per discussion with @BenjaminHolland, I'm going to close this. We talked about first filing an issue to demonstrate the desired change in the experience for users, and then based on the different behaviours we decide we want to support, we can figure out a callback API if needed. In the meantime, let's keep the interface as small as possible so that it's easy to maintain.
