### ISSUE TITLE
There is still feedback after pressing Reset Code

### ISSUE THREAD

**Issue by theresa-lee** [google/tie#479]
I'm not sure if this is considered the same root problem as #279, but when pressing the 'Reset Code' button, it clears the full queue of feedback, but then the feedback loads the latest feedback. I think this might be confusing since your code is reset and the feedback shown is probably wrong.

**Comment by rabidbit** [comment]
Agree. I think if code is reset, last feedback should not show on reload.

**Comment by rabidbit** [comment]
IMO, I think if the user resets their code, the feedback should not reset (because there should be a reset feedback button too, which is not yet implemented).

However, if the user resets their code and then reloads the page, then I think it makes sense to clear the feedback as well. If the user did not reset their code and reloaded the page, I think it makes sense to show the last output.
