### ISSUE TITLE
Displaying 'Next' when we don't have more than one question ready

### ISSUE THREAD

**Issue by theresa-lee** [google/tie#482]
When you complete a question, the Next thing pops up over the coding window. But we don't any more questions to navigate to (at this point) and also pressing next brings up a popup that congratulates you on finishing the problem, which seems redundant as the feedback window already tells you that.

**Comment by rabidbit** [comment]
Next button makes sense for a sequence of questions, which we do not currently have and are unclear whether we want to implement that in the near future.

For now, since we only have one question, are using a chat conversation experience, and have conditioned the user to look at the chat window for feedback, why don't we remove the Next button and overlay and instead add an emoji to the congratulatory feedback? This could keep the UI/UX simple while giving the user a little nicer reward beyond congratulatory text.

**Comment by rabidbit** [comment]
Fixed in #484
