### ISSUE TITLE
Wrong language detection always triggers "It looks like you haven't changed your code."

### ISSUE THREAD

**Issue by rabidbit** [google/tie#534]
Repro:
1. Trigger wrong language detection (e.g., use '!' instead of 'not' in an if statement)
2. Fix the error (e.g., use 'not instead of '!')
3. Do anything
4. Note that it always says "It looks like you haven't changed your code. Try addressing the error before you run again." regardless of whether and how you change the code.

**Comment by seanlip** [comment]
This is now fixed in [this commit](https://github.com/google/tie/commit/f88c4d928f7c7424cc9cb21d6c998493e667c9c5) in the fallback-redux branch. The fix is a temporary one (as is that whole branch) and a better fix would be to implement the full learner state refactor (which I haven't gotten around to doing yet).

Here is what the issue was: when triggering the "you haven't changed your code" message, we are currently comparing the user's code evaluation result to the last one stored in the TranscriptService. However, when code fails due to a prerequisite check, the code evaluation result that was stored is null (because the code wasn't evaluated). We were treating this, by default, as a "code has not changed". The fix that was made in the aforementioned commit reverses this.

There is a downside to this change, which is that repeated submits of the same code may _not_ trigger a "your code has not changed" error when they really should. However, I think that is OK and is better than the alternative. In addition, there will be some clear error to fix (like a failing prerequisite check) and it should be straightforward to make that fix, without which TIE can't really give more detailed feedback anyway. So I think the fix resolves this issue, at least in the short term.
