### ISSUE TITLE
(a) Make it more clear what language the coding window is in and (b) Not clear that 's' should be treated as a string.

### ISSUE THREAD

**Issue by rabidbit** [google/tie#572]

**Comment by seanlip** [comment]
I'm fine with (a), but let's get @rabidbit's opinion because I think we had something like this before and removed it when we realized that it was causing confusion due to our currently supporting only one language.

For (b), str is a keyword in Python. I actually think `s` is a reasonably standard name for a string, though we could also call it input_string if we wanted to be super explicit. But that's a bit clunky. @rabidbit do you have any suggestions for what to do here, or more clarification on the underlying problem?

**Comment by rabidbit** [comment]
Drop-down with only one language (whether or not other languages listed are disabled) is an undesirable UX because it only serves to note to the user our language limitation. This issue may go away if/when we support multi-lang for both server and stand-alone.

How about adding comments, like this?...

```
# Python version 2.7

def reverseWords(s):
    # This reverseWords method processes a string (s)
    
    return ""
```

**Comment by rabidbit** [comment]
@seanlip 

Per #575 [thread](https://github.com/google/tie/pull/575#discussion_r189112405)... OK, how about we do the below (keep info on input as a comment but add language name next to the Reset Code button)? It will be simple enough to change when we implement multi-lang. Re: having to add a comment for each question with specs on the input, that seems OK to me, since every question will be different and will use different input specs.

![language-specification](https://user-images.githubusercontent.com/25493966/40206153-b0950d6c-59e3-11e8-83d8-79ec777a6e0c.png)

**Comment by seanlip** [comment]
Yes, I'm fine with having the input specs comment be per-question.

In general I think the suggestion you have here works fine from a technical perspective. Not totally sure about UI though -- seems a bit weird to have different font sizes next to each other, and I don't know if more delineation between the bold text and the link next to it is needed. Might want to double-check quickly with Amy?

**Comment by rabidbit** [comment]
SGTM
