### ISSUE TITLE
client/question/question.html URL seems redundant

### ISSUE THREAD

**Issue by eyurko** [google/tie#577]
Could we move the HTML files out of their folders and up into the client/ directory? This seems like it would eliminate that redundancy.

**Comment by rabidbit** [comment]
SGTM

**Comment by rabidbit** [comment]
Hmm... thinking about why this is like this... I would guess that it was when we expected to have multiple questions. In that case, we would have used client/question/reversewords.html
Perhaps we changed reversewords.html to question.html, because we only had one question at the time. In that case, we should consider that we will have multiple questions. Even if we don't have a navigation UI to browse through them, since TIE may be embedded into a page that handles presentation/navigation across questions.

**Comment by seanlip** [comment]
Fixed in #578
