### ISSUE TITLE
Clicking "Reset Code" does not clear the feedback window.

### ISSUE THREAD

**Issue by kchen05** [google/tie#622]
* When a user clicks "Reset Code", this should reset the code as well as the feedback.
* Currently the code resets but the feedback flashes yellow briefly before remaining there.

**Comment by rabidbit** [comment]
Clear Feedback button should clear the feedback. So, WAI. However, the feedback bubbles flashing is not intended and should not happen. This is a lower priority issue. Marking P2.

**Comment by rabidbit** [comment]
This issue was for when "reset feedback" and "reset code" buttons exit. The problem was that since feedback was being reloaded from local storage, it would render as if for the first time (all the feedback speech balloons would disappear, reappear, and flash). Because we are replacing these two distinct functions with "start over", this is no longer an issue; the "start over" button would clear all the feedback. In the case where everything is reset, the re-rendering of the initial speech balloon is not really an issue.
