### ISSUE TITLE
Problems of input code screen

### ISSUE THREAD

**Issue by xiaoyig** [google/tie#82]
1. Cannot add a character in middle.
When users want to add 'c' in middle of 'abde', users will expect it becomes 'abcde'. But the actual result turns to be 'abce', where the new character 'c' covers the old character 'd' instead of adding itself between 'b' and 'd' in 'abde'. 

2. Cannot scale as two other output screens.

**Comment by seanlip** [comment]
Thanks, @xiaoyig. Would you mind providing repro insructions (from scratch), expected/observed behavior, and a screenshot, similar to #83?

Also, I'm not sure whether this issue is actually meant to be two separate issues. If that's the case, would you mind filing them separately? It's totally fine to close this one and file two more in its place.

Thanks!

**Comment by xiaoyig** [comment]
Try to start a new issue
