### ISSUE TITLE
Last Question (encode and decode)

### ISSUE THREAD

**Issue by huynhducloi** [google/tie#86]
The problem statement is not so clear. We don't know what to expect as the result of the decoder. The problem said something about one-to-one mapping between the encoder and decoder, 23xa means 2aaa and not 23 of 'a'. However, it is not just clear in the problem statement.

**Comment by eyurko** [comment]
This is an important distinction -- interview question prompts are somewhat intentionally vague, as they are  not necessarily a spec. We want students to consider possible edge cases without us having to enumerate over all possible edge cases, rather than having them build a program to our exact specifications. This problem's difficulty lies, in part, in the vague encoding requirement (and it is a difficult encoding to get right).

With that in mind, what would you need to do to resolve this issue?

**Comment by seanlip** [comment]
(Note: please also see notes on #88.)
