### ISSUE TITLE
[Sample question issue] RLE question gives confusing description

### ISSUE THREAD

**Issue by jianhaolyu** [google/tie#93]
In the last phase of this question, the user are required to encode the word in a comprehensible manner, in which "5aaaa" can be decoded properly.
However, the most straight forward way is to encode "5" as "1x5", which conflict with the previous phase's requirement(encoding should be as short as possible).

**Comment by seanlip** [comment]
Thanks, @jianhaolyu!

@eyurko -- any thoughts?

**Comment by eyurko** [comment]
Seems like the messaging should be "provided the encoding is correct / reversible, it should be as short as possible", so that the student prioritizes correctness over brevity.

**Comment by jianhaolyu** [comment]
@eyurko what means "prioritize"? Are students supposed to fulfill both requirements? Since encoding "5" as "1x5" totally violate the brevity requirement.

**Comment by eyurko** [comment]
So, short answer, there's no good way to create a perfect encoding scheme. Part of the last task is understanding that and trying to build something that prioritizes correctness but generally tries to be as short as possible. I think, in the case you've specified, you should not return 1x5, because there's no way to have a decoder misinterpret 5 (or any string of length <= 2). In general, what I'm trying to say is that we should relax the brevity "requirement" from the first segment into more of a suggestion.

If you're shooting for a mix of brevity and correctness, 1x54xa is actually not better (it's longer), but the best version would be either returning 5aaaa or 5a3xa. It seems like it could be worth mentioning "you may find it necessary to relax the brevity requirement in order to accomplish this, but still try to keep the encoded strings as short as possible" as a hint of some kind, but I wouldn't necessarily mention that to the student first if I were asking this as an interview question (and I have, in the past).

**Comment by seanlip** [comment]
Handled in #256.
