### ISSUE TITLE
[Question Schema] Test cases can be exhaustedly listed out

### ISSUE THREAD

**Issue by xchenan** [google/tie#97]
Since the test cases, which are quite few and rather simple, are shown on screen with their correct answers once failed, challengers can list out all test cases as predicates in their codes and 'cheat'.

**Comment by eyurko** [comment]
So, first off, for consistency's sake, please provide repro steps from a clean copy and a screenshot of the error in progress.

**Comment by eyurko** [comment]
Second, we have discussed this a few times with the team and there are a few different schools of thought, here:

1) If a student wants to cheat, they are really just hurting themselves, since it's a prep tool. This is a similar mindset to the idea that Cracking the Coding Interview / Programming Interviews Exposed do have solutions in the book, so you _could_ read them that way if you wanted to, though you're costing yourself the educational experience.
2) On the other hand, it is possible to build new correctness tests pretty easily by generating random inputs and then running the solution code over those inputs. This would allow us to very easily create an exhaustive list of test cases such that no student would ever _really_ want to enumerate over all of them.

What are your thoughts?

**Comment by xchenan** [comment]
Repo steps:

1. Open "app.html".

2. Navigate to Question 2, which has three tasks in total.

3. Do code as follows then click "Run", which makes the Judge report a test failure:
![image](https://cloud.githubusercontent.com/assets/6829866/24670975/eaa16452-1924-11e7-8d15-46f1efcf32b0.png)

4. Put a specific predicate for dealing with this test case. The code now passes the first test, but fails on another one:
![image](https://cloud.githubusercontent.com/assets/6829866/24671062/353b9cf8-1925-11e7-8cdd-f707d9d2b00a.png)
In such way challengers are able to enumerate over all test cases created by engineers.

5. Try out all cases and put them all in predicates. Now the code is able to finish Task One:
![image](https://cloud.githubusercontent.com/assets/6829866/24671346/0df2d14c-1926-11e7-965f-b482b29bb848.png)

Proposal:
1. Either generate some random test cases or
2. Hide some test cases from challengers

**Comment by BenjaminHolland** [comment]
Even if you add randomized test cases, until you do some sort of encryption , obfuscation, or other protection on the test cases, "enterprising" users can still simply go into the questions and change/disable them. In both cases, I'm not actually sure why they're bothering to use the app at all.

Hiding test cases seems unproductive. Nothing is more frustrating than failing and receiving no directional feedback. I'd only consider this acceptable if every test case was accompanied by an associated "hint". While it may be more thematic to have the interviewer give you a stony-faced silent stare when you're bombing, I'm skeptical it has any real value while preparing for an interview.

That said, if it's going to be used as a teaching aid for a grade in class, it might be useful to provide check sums for the question files that are distributed separately from the main project. Perhaps calculate them every push?

**Comment by seanlip** [comment]
We talked about this in a team meeting, and decided not to take action on this. TIE is intended to be a formative tool, and preventing cheating is not one of its goals.
